# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c78ea0b1fa225a86a8a90ac3ccee1a70c9ce837a90f16ae9af0d05b63e94c5dd691d12f65943d3b30e584057b3b4a8745547385c03b60fa5c3ee69dcbf6f78ed

test:
  secret_key_base: f32862ae2ff7bfd51f392c7aafd64e81efe1d0b6bb029d10ae0384df6d56653ad62777ee07eafd2639cbb519aa72a9e57b5ccd31d0656d65a3aa6c90c1912a60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
